### ISSUE TITLE
[BUG] Does not download videos.

### ISSUE THREAD

**Issue by Rich700000000000** [dixudx/tumblr-crawler#12]
I just attempted to copy a tumblr blog, and none of the videos were downloaded. The blog in question had dozens of videos, and only a few non video posts.

**Comment by dixudx** [comment]
@Rich700000000000 Have you commented [L137](https://github.com/dixudx/tumblr-crawler/blob/master/tumblr-photo-video-ripper.py#L137)?

If not, would you mind to providing me the blog url ?

**Comment by kyeolee89** [comment]
@dixudx It seems to be based on hdUrl. Some videos have hdUrl set to false. How do you change it based on "source src ="?

**Comment by dixudx** [comment]
Please refer to PR #10 for hdUrl, which has already been merged. @hquan Thanks for your work. This PR will first try to match `hdUrl`. If no results matched, the matching rule will be the older one. 

@Rich700000000000 @kyeolee89 Please pull the latest code. And try again.

**Comment by kyeolee89** [comment]
@dixudx @hquan Please check the sample site with "honorwings-blog". I think we should have "hd_match.group (2)" instead of "hd_match" on line 58. Check out the sample site and it will include a YouTube link. And the 63th line does not contain line breaks in the regular expression, so it is not processed. You must modify it to include line breaks with the "re.DOTALL" option. After that, we need to download various services such as YouTube and Vimeo. Please check PR #13

**Comment by dixudx** [comment]
@kyeolee89 I've already merged PR #14. Please rebase your codes to include `re.DOTALL`
