### ISSUE TITLE
Access Denied when downloading some urls. Those incompleted files with size 243B should be deleted.

### ISSUE THREAD

**Issue by a2259721** [dixudx/tumblr-crawler#17]
经常下载视频会fail

**Comment by dixudx** [comment]
[请配置proxy](https://github.com/dixudx/tumblr-crawler/blob/master/README_CN.md#使用代理-可选)

**Comment by a2259721** [comment]
已经设置代理，每个视频都是下一半fail的

**Comment by dixudx** [comment]
方便透露一下url吗

**Comment by a2259721** [comment]
发你邮箱吧

**Comment by dixudx** [comment]
@a2259721 I've already fixed this bug.

Some of those unfinished files with size 243B are due to "Access Denied" when downloading.

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>*********</RequestId>
<HostId>
********************
</HostId>
</Error>
```
 Only some metadata are retrieved and written to those files.

In [this new patchset](https://github.com/dixudx/tumblr-crawler/commit/c0064fe0815f47cfc9f014584794eb2df2c77044), those files will be deleted.
