### ISSUE TITLE
Help Me!

### ISSUE THREAD

**Issue by Dashwood2** [dixudx/tumblr-crawler#40]
I used the script , but it doesn't work with the alert：

![screenshot from 2017-09-07 18-54-15](https://user-images.githubusercontent.com/22023847/30160442-ec275dae-93fe-11e7-92c2-c81265355632.png)

**Comment by dixudx** [comment]
@Dashwood2  Please [install all dependencies first](https://github.com/dixudx/tumblr-crawler#prerequisite).


```
$ pip install -r requirements.txt
```

**Comment by Dashwood2** [comment]
Hi dixudx,
I am happy your answer is so fast. I  did that following the README on my Fedora25, and it worked well. But it didn't work in recent days. I don't how to do. You can see the result I had run the command :"pip install -r requirements.txt"
![screenshot from 2017-09-08 09-26-23](https://user-images.githubusercontent.com/22023847/30192132-17eafda0-9478-11e7-9374-5600a726a2da.png)
_Thank You!_

**Comment by dixudx** [comment]
run `pip list | grep urllib3` to see whether it has been successfully installed.

**Comment by Dashwood2** [comment]
I think Yes!


![screenshot from 2017-09-08 09-35-27](https://user-images.githubusercontent.com/22023847/30192283-50990f10-9479-11e7-9c37-a40ca90bdf6a.png)

**Comment by dixudx** [comment]
Found the import error is invoked by `requests`.

Please help verify whether `requests` has been installed successfully.

**Comment by Dashwood2** [comment]
![screenshot from 2017-09-08 09-40-59](https://user-images.githubusercontent.com/22023847/30192384-fc70977c-9479-11e7-9775-995af6820903.png)

**Comment by dixudx** [comment]
This seems to be a system environment problem.

Have some workarounds for such problems,

* use [`virtualenv`](http://docs.python-guide.org/en/latest/dev/virtualenvs/) to setup a new virtual environment for Python; This is the most convenient way to get rid of such problems.

* Since the packages has already been installed, please help check the python import path, `*.pth` files and etc; This would be a tricky way. If you've got enough experience on Python, I think you will get a lot of fun to find it.

I'd recommend the first option for you.

**Comment by Dashwood2** [comment]
Thank You!
I have found the problem. Because I have installed the python2.7 and python3.To solve the problem as the following:
python3 -m pip install  -r requirements.txt
