### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by ghost** [dixudx/tumblr-crawler#66]

**Comment by dixudx** [comment]
> 'ImportError: no module named requests' even though I checked and reinstalled 'requests' module
> when I try to import it in IDLE, I have no problems

@firstneithernorlast Seems you have not set correctly in your terminal. Please check the `pip` and `python` version, `PYTHONPATH` and etc in your terminal. Something must be mis-configured.

> infinite amount of "Unknown xml-vulnerabilities from URL http://sitename.tumblr.com/api/read?type=photo&num=50&start=0"

Refer to #53. This is because the response data contains not well-formed characters. Also you can refer [#31](https://github.com/dixudx/tumblr-crawler/issues/31#issuecomment-298218368) by setting `MEDIA_NUM` to a larger value, for example 100. Give it a try.

**Comment by firstneithernorlast** [comment]
There were some problems with my pip I think, but I got it working somehow, thank you for your time!
